# Generated by Django 6.0.5 on 2026-06-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Review', 'In Review'), ('Escalated', 'Escalated'), ('Resolved', 'Resolved')], default='Pending', max_length=20),
        ),
    ]
