# Generated by Django 6.0.5 on 2026-07-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=100)),
                ('openings', models.PositiveIntegerField(default=1)),
                ('location', models.CharField(max_length=100)),
                ('employment_tyoe', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship'), ('Contract', 'Contract'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], max_length=20)),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('skills', models.TextField(blank=True, help_text='Enter one skill per line', null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Hirirng', 'Hiring'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
