# Generated by Django 6.0.5 on 2026-07-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobopening',
            old_name='employment_tyoe',
            new_name='employment_type',
        ),
        migrations.AddField(
            model_name='jobopening',
            name='experience_required',
            field=models.CharField(default='Fresher', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Hiring', 'Hiring'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
    ]
