# Generated by Django 6.0.5 on 2026-07-22 06:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_priority_notification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_group',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
