# Generated by Django 6.0.5 on 2026-06-06 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Resume', 'Resume'), ('Degree Certificate', 'Degree Certificate'), ('Experience Certificate', 'Experience Certificate'), ('Offer Letter', 'Offer Letter')], max_length=100)),
                ('document', models.FileField(upload_to='employee_documents/')),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Verified', 'Verified'), ('Pending Verification', 'Pending Verification')], default='Pending Verification', max_length=30)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
