# Generated by Django 6.0.5 on 2026-06-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='payslips/'),
        ),
    ]
